### ISSUE TITLE
[Feat] 작심 관련 엔티티 생성

### ISSUE THREAD

**Issue by HeWillGoTillTheEnd** [ConnectingChips/ConnectingChips-Back#19]
## Description
ERD에 따라 작심 관련 엔티티를 생성합니다.
##To-do
- [x] 작심 종류 엔티티 생성 
- [x] 작심 엔티티 생성
- [x] 참여한 작심 엔티티 생성

##ETC
