### ISSUE TITLE
[Feat] 게시물 + 댓글 글자 수 제한걸기

### ISSUE THREAD

**Issue by bnfkim** [ConnectingChips/ConnectingChips-Back#224]
## Description

##To-do
- [x] 게시물 엔티티 수정
- [x] 댓글 엔티티 수정
- [x] 답글 엔티티 수정

##ETC
