### ISSUE TITLE
[Feat] send-authentication-email

### ISSUE THREAD

**Issue by SBSun** [ConnectingChips/ConnectingChips-Back#238]
## Description
send-authentication-email
##To-do
- [x] email 의존성 추가 및 Config
- [x] email 보내기 기능
- [x] email 검증 기능

##ETC
